# Site settings
title: Valentin Sawadski
author:
    twitter: _vsaw
    github: vsaw
    bio: >
      This is about hacking, technological advances and how to seize the
      opportunity! All from an entrepreneurial angle and based on personal
      experiences.
    email_md5: 852b85aa04b05cb283891c04b7821a44

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about.html
projects_path: projects.html

# Build settings
markdown: redcarpet

# GitHub Page Settings
highlighter: pygments
safe: true
lsi: false

# Local Environment Cleanup
exclude: ["Vagrantfile", "Vagrant", "Gemfile", "Gemfile.lock"]
