# Site settings


# Build settings
markdown: redcarpet

# GitHub Page Settings
highlighter: pygments
safe: true
lsi: false

# Local Environment Cleanup
exclude: ["Vagrantfile", "Vagrant", "Gemfile", "Gemfile.lock"]
